version: '2'
services:
  nodejs-build:
    build:
      context: $PWD/maven-docker-build
      dockerfile: $PWD/maven-docker-build/DockerfileUI
    image: nodebuild:14.15
    volumes:
      - $PWD/../:/flowgate-build
      - $PWD/log:/log
    networks:
      - ui-network
    container_name: nodejs-build-container

networks:
  ui-network:
