#!/bin/bash
#
#Copyright 2019 VMware, Inc.
#SPDX-License-Identifier: BSD-2-Clause
#

echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createAnAsset","resource":[{"pattern":"/v1/assets","httpMethod":"POST","sortWeight":"2"}]}' > createAnAsset
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createAssets","resource":[{"pattern":"/v1/assets/batchoperation","httpMethod":"POST","sortWeight":"2"}]}' > createAssets
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAsset","resource":[{"pattern":"/v1/assets/**","httpMethod":"GET","sortWeight":"1"}]}' > readAsset
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetBySource","resource":[{"pattern":"/v1/assets/source/**","httpMethod":"GET","sortWeight":"5"}]}' > readAssetBySource
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetByAssetName","resource":[{"pattern":"/v1/assets/name/**","httpMethod":"GET","sortWeight":"97"}]}' > readAssetByAssetName
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetBySourceAndType","resource":[{"pattern":"/v1/assets/source**/type/**","httpMethod":"GET","sortWeight":"96"}]}' > readAssetBySourceAndType
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetByType","resource":[{"pattern":"/v1/assets/type/**","httpMethod":"GET","sortWeight":"2"}]}' > readAssetByType
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readMappedAsset","resource":[{"pattern":"/v1/assets/mappedasset/category/**","httpMethod":"GET","sortWeight":"100"}]}' > readMappedAsset
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetByKeywords","resource":[{"pattern":"/v1/assets/page/**","httpMethod":"GET","sortWeight":"100"}]}' > readAssetByKeywords
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetByPduIsNull","resource":[{"pattern":"/v1/assets/pdusisnull","httpMethod":"GET","sortWeight":"1"}]}' > readAssetByPduIsNull
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateAsset","resource":[{"pattern":"/v1/assets","httpMethod":"PUT","sortWeight":"1"}]}' > updateAsset
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteAsset","resource":[{"pattern":"/v1/assets/**","httpMethod":"DELETE","sortWeight":"2"}]}' > deleteAsset
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createRealTimeSensorDatas","resource":[{"pattern":"/v1/assets/sensordata/batchoperation","httpMethod":"POST","sortWeight":"10"}]}' > createRealTimeSensorDatas
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createRealTimeSensorData","resource":[{"pattern":"/v1/assets/**/sensordata","httpMethod":"POST","sortWeight":"10"}]}' > createRealTimeSensorData
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readServerSensorData","resource":[{"pattern":"/v1/assets/**/serversensordata","httpMethod":"GET","sortWeight":"10"}]}' > readServerSensorData
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createServerMapping","resource":[{"pattern":"/v1/assets/mapping","httpMethod":"POST","sortWeight":"10"}]}' > createServerMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetsByVROID","resource":[{"pattern":"/v1/assets/vrops/**","httpMethod":"GET","sortWeight":"1"}]}' > readAssetsByVROID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateServerMapping","resource":[{"pattern":"/v1/assets/mapping","httpMethod":"PUT","sortWeight":"10"}]}' > updateServerMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"mergeServerMapping","resource":[{"pattern":"/v1/assets/mapping","httpMethod":"PUT","sortWeight":"10"}]}' > mergeServerMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readUnMappedServers","resource":[{"pattern":"/v1/assets/mapping/unmappedservers","httpMethod":"GET","sortWeight":"30"}]}' > readUnMappedServers
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readMappingsByVROIDAndPage","resource":[{"pattern":"/v1/assets/mapping/vrops/**/page/**/pagesize/**","httpMethod":"GET","sortWeight":"100"}]}' > readMappingsByVROIDAndPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readMappingsByVCIDAndPage","resource":[{"pattern":"/v1/assets/mapping/vc/**/page/**/pagesize/**","httpMethod":"GET","sortWeight":"100"}]}' > readMappingsByVCIDAndPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createHostNameAndIPMapping","resource":[{"pattern":"/v1/assets/mapping/hostnameip","httpMethod":"POST","sortWeight":"10"}]}' > createHostNameAndIPMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readHostNameAndIPMapping","resource":[{"pattern":"/v1/assets/mapping/hostnameip/ip/**","httpMethod":"GET","sortWeight":"30"}]}' > readHostNameAndIPMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readAssetsByVCID","resource":[{"pattern":"/v1/assets/vc/**","httpMethod":"GET","sortWeight":"10"}]}' > readAssetsByVCID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createFacilitySoftwareConfig","resource":[{"pattern":"/v1/facilitysoftware","httpMethod":"POST","sortWeight":"5"}]}' > createFacilitySoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readFacilityByID","resource":[{"pattern":"/v1/facilitysoftware/**","httpMethod":"GET","sortWeight":"5"}]}' > readFacilityByID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readFacilityByType","resource":[{"pattern":"/v1/facilitysoftware/type/**","httpMethod":"GET","sortWeight":"5"}]}' > readFacilityByType
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readFacilityByPage","resource":[{"pattern":"/v1/facilitysoftware/page/**","httpMethod":"GET","sortWeight":"15"}]}' > readFacilityByPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"facilityServerSyncDataByServerId","resource":[{"pattern":"/v1/facilitysoftware/syncdatabyserverid/**","httpMethod":"POST","sortWeight":"8"}]}' > facilityServerSyncDataByServerId
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteFacilitySoftwareConfig","resource":[{"pattern":"/v1/facilitysoftware/**","httpMethod":"DELETE","sortWeight":"3"}]}' > deleteFacilitySoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateFacilitySoftwareConfig","resource":[{"pattern":"/v1/facilitysoftware","httpMethod":"PUT","sortWeight":"3"}]}' > updateFacilitySoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateFacilitySoftwareConfigStatus","resource":[{"pattern":"/v1/facilitysoftware/status","httpMethod":"PUT","sortWeight":"4"}]}' > updateFacilitySoftwareConfigStatus
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"startFullMappingAggregation","resource":[{"pattern":"/v1/jobs/mergeservermapping","httpMethod":"POST","sortWeight":"6"}]}' > startFullMappingAggregation
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"generateServerPDUMapping","resource":[{"pattern":"/v1/jobs/pduservermapping","httpMethod":"POST","sortWeight":"6"}]}' > generateServerPDUMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"syncHostnameByIp","resource":[{"pattern":"/v1/jobs/synchostnamebyip/**","httpMethod":"POST","sortWeight":"6"}]}' > syncHostnameByIp
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readVROJobs","resource":[{"pattern":"/v1/jobs/vrojobs","httpMethod":"GET","sortWeight":"6"}]}' > readVROJobs
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readVCJobs","resource":[{"pattern":"/v1/jobs/vcjobs","httpMethod":"GET","sortWeight":"6"}]}' > readVCJobs
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readJobByType","resource":[{"pattern":"/v1/jobs/type/**","httpMethod":"GET","sortWeight":"6"}]}' > readJobByType
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"tempHumidityMapping","resource":[{"pattern":"/v1/jobs/temphumiditymapping/fullsync/**","httpMethod":"POST","sortWeight":"1"}]}' > tempHumidityMapping
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createSddcSoftwareConfig","resource":[{"pattern":"/v1/sddc","httpMethod":"POST","sortWeight":"8"}]}' > createSddcSoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteSddcSoftwareConfig","resource":[{"pattern":"/v1/sddc/**","httpMethod":"DELETE","sortWeight":"8"}]}' > deleteSddcSoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateSddcSoftwareConfig","resource":[{"pattern":"/v1/sddc/","httpMethod":"PUT","sortWeight":"8"}]}' > updateSddcSoftwareConfig
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateSddcSoftwareConfigStatus","resource":[{"pattern":"/v1/sddc/status","httpMethod":"PUT","sortWeight":"9"}]}' > updateSddcSoftwareConfigStatus
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSddcSoftwareConfigByID","resource":[{"pattern":"/v1/sddc/**","httpMethod":"GET","sortWeight":"8"}]}' > readSddcSoftwareConfigByID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"syncDataByServerId","resource":[{"pattern":"/v1/sddc/syncdatabyserverid/**","httpMethod":"POST","sortWeight":"8"}]}' > syncDataByServerId
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readVROByUser","resource":[{"pattern":"/v1/sddc/user/vrops","httpMethod":"GET","sortWeight":"8"}]}' > readVROByUser
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSddcSoftwareConfigByVC","resource":[{"pattern":"/v1/sddc/vc","httpMethod":"GET","sortWeight":"8"}]}' > readSddcSoftwareConfigByVC
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSddcSoftwareConfigByUserAndPage","resource":[{"pattern":"/v1/sddc/page/**","httpMethod":"GET","sortWeight":"12"}]}' > readSddcSoftwareConfigByUserAndPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readVROsSddcSoftwareConfigByUser","resource":[{"pattern":"/v1/sddc/vrops","httpMethod":"GET","sortWeight":"8"}]}' > readVROsSddcSoftwareConfigByUser
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSddcSoftwareConfigByTypeAndUser","resource":[{"pattern":"/v1/sddc/type/**","httpMethod":"GET","sortWeight":"10"}]}' > readSddcSoftwareConfigByTypeAndUser
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createSensorSetting","resource":[{"pattern":"/v1/sensors/setting","httpMethod":"POST","sortWeight":"1"}]}' > createSensorSetting
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSensorSettingByID","resource":[{"pattern":"/v1/sensors/setting/**","httpMethod":"GET","sortWeight":"6"}]}' > readSensorSettingByID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSensorSettingsByPage","resource":[{"pattern":"/v1/sensors/setting/page/**/pagesize/**","httpMethod":"GET","sortWeight":"10"}]}' > readSensorSettingsByPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateSensorSetting","resource":[{"pattern":"/v1/sensors/setting","httpMethod":"PUT","sortWeight":"2"}]}' > updateSensorSetting
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteSensorSetting","resource":[{"pattern":"/v1/sensors/setting/**","httpMethod":"DELETE","sortWeight":"2"}]}' > deleteSensorSetting
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteUser","resource":[{"pattern":"/v1/auth/user/**","httpMethod":"DELETE","sortWeight":"1"}]}' > deleteUser
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateUser","resource":[{"pattern":"/v1/auth/user","httpMethod":"PUT","sortWeight":"3"}]}' > updateUser
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readUserByID","resource":[{"pattern":"/v1/auth/user/**","httpMethod":"GET","sortWeight":"1"}]}' > readUserByID
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readUserByUserName","resource":[{"pattern":"/v1/auth/user/username/**","httpMethod":"GET","sortWeight":"10"}]}' > readUserByUserName
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readUserByPage","resource":[{"pattern":"/v1/auth/user/page/**","httpMethod":"GET","sortWeight":"10"}]}' > readUserByPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readUsers","resource":[{"pattern":"/v1/auth/user/users","httpMethod":"GET","sortWeight":"3"}]}' > readUsers
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"createRole","resource":[{"pattern":"/v1/auth/role","httpMethod":"POST","sortWeight":"1"}]}' > createRole
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readRole","resource":[{"pattern":"/v1/auth/role/**","httpMethod":"GET","sortWeight":"1"}]}' > readRole
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readRolesByPage","resource":[{"pattern":"/v1/auth/role","httpMethod":"GET","sortWeight":"10"}]}' > readRolesByPage
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"deleteRole","resource":[{"pattern":"/v1/auth/role/**","httpMethod":"DELETE","sortWeight":"1"}]}' > deleteRole
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"updateRole","resource":[{"pattern":"/v1/auth/role","httpMethod":"PUT","sortWeight":"1"}]}' > updateRole
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readPrivileges","resource":[{"pattern":"/v1/auth/privileges","httpMethod":"GET","sortWeight":"1"}]}' > readPrivileges
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"readSystemSummary","resource":[{"pattern":"/v1/summary/systemsummary","httpMethod":"GET","sortWeight":"1"}]}' > readSystemSummary
echo '{"_class":"com.vmware.flowgate.common.model.PrivilegeResourceMapping","privilegeName":"Default_Access_Privilege","resource":[{"pattern":"/v1/auth/logout","httpMethod":"GET","sortWeight":"1"},{"pattern":"/v1/auth/user","httpMethod":"POST","sortWeight":"1"},{"pattern":"/v1/auth/token","httpMethod":"POST","sortWeight":"1"},{"pattern":"/v1/auth/token/refresh","httpMethod":"GET","sortWeight":"1"}]}' > Default_Access_Privilege
echo '{"_class":"com.vmware.flowgate.common.model.WormholeRole","roleName":"admin","privilegeNames":["readAssetBySource","updateFacilitySoftwareConfigStatus","updateSddcSoftwareConfigStatus","readSystemSummary","tempHumidityMapping","readUserByUserName","facilityServerSyncDataByServerId","syncDataByServerId","readVROByUser","readUnMappedServers","readAssetsByVCID","readPrivileges","createAnAsset","createAssets","readAsset","readAssetByAssetName","readAssetBySourceAndType","readAssetByType","readMappedAsset","readAssetByKeywords","readAssetByPduIsNull","updateAsset","deleteAsset","createRealTimeSensorDatas","createRealTimeSensorData","readServerSensorData","createServerMapping","readAssetsByVROID","updateServerMapping","mergeServerMapping","readMappingsByVROIDAndPage","readMappingsByVCIDAndPage","createHostNameAndIPMapping","createFacilitySoftwareConfig","readFacilityByID","readFacilityByType","readFacilityByPage","deleteFacilitySoftwareConfig","updateFacilitySoftwareConfig","startFullMappingAggregation","generateServerPDUMapping","syncHostnameByIp","readVROJobs","readVCJobs","readJobByType","createSddcSoftwareConfig","deleteSddcSoftwareConfig","updateSddcSoftwareConfig","readSddcSoftwareConfigByID","readSddcSoftwareConfigByVC","readSddcSoftwareConfigByUserAndPage","readVROsSddcSoftwareConfigByUser","readSddcSoftwareConfigByTypeAndUser","createSensorSetting","readSensorSettingByID","readSensorSettingsByPage","updateSensorSetting","deleteSensorSetting","readHostNameAndIPMapping","deleteUser","updateUser","readUserByID","readUserByPage","readUsers","createRole","readRole","readRolesByPage","deleteRole","updateRole","Default_Access_Privilege"]}' > wormholeRole_default_admin
echo '{"_class":"com.vmware.flowgate.common.model.WormholeRole","roleName":"api","privilegeNames":["readAssetBySource","updateSddcSoftwareConfigStatus","readVROByUser","readAssetsByVCID","readAsset","readAssetByAssetName","readAssetBySourceAndType","readAssetByType","readMappedAsset","readAssetByKeywords","readAssetByPduIsNull","createServerMapping","readAssetsByVROID","updateServerMapping","mergeServerMapping","readMappingsByVROIDAndPage","readMappingsByVCIDAndPage","createSddcSoftwareConfig","deleteSddcSoftwareConfig","updateSddcSoftwareConfig","readSddcSoftwareConfigByID","readSddcSoftwareConfigByVC","readSddcSoftwareConfigByUserAndPage","readVROsSddcSoftwareConfigByUser","readSddcSoftwareConfigByTypeAndUser","readHostNameAndIPMapping","Default_Access_Privilege"]}' > wormholeRole_default_api
echo '{"_class":"com.vmware.flowgate.common.model.WormholeRole","roleName":"user","privilegeNames":["readPrivileges","updateSddcSoftwareConfigStatus","updateUser","syncDataByServerId","readUserByUserName","readVROByUser","readAssetsByVCID","readAsset","readAssetByAssetName","readAssetBySourceAndType","readAssetByType","readMappedAsset","readAssetByKeywords","readAssetByPduIsNull","createServerMapping","readAssetsByVROID","updateServerMapping","mergeServerMapping","readMappingsByVROIDAndPage","readMappingsByVCIDAndPage","createSddcSoftwareConfig","deleteSddcSoftwareConfig","updateSddcSoftwareConfig","readSddcSoftwareConfigByID","readSddcSoftwareConfigByVC","readSddcSoftwareConfigByUserAndPage","readVROsSddcSoftwareConfigByUser","readSddcSoftwareConfigByTypeAndUser","Default_Access_Privilege"]}' > wormholeRole_default_user
echo '{"_class":"com.vmware.flowgate.common.model.WormholeUser","userName":"admin","password":"$2a$10$FZKc/4rF0.QWyxNiFyFyzO9CQPQ0NiggFS2BqmQw2M.biqOVH5/wu", "roleNames" : [ "admin" ]}' > WormholeUser_default_admin

zip -m database.zip createAnAsset createAssets readAsset readAssetByAssetName readAssetBySourceAndType readAssetByType readMappedAsset readAssetByKeywords readAssetByPduIsNull updateAsset deleteAsset createRealTimeSensorDatas createRealTimeSensorData readServerSensorData createServerMapping readAssetsByVROID updateServerMapping mergeServerMapping readUnMappedServers readMappingsByVROIDAndPage readMappingsByVCIDAndPage createHostNameAndIPMapping readHostNameAndIPMapping readAssetsByVCID createFacilitySoftwareConfig readFacilityByID readFacilityByType readFacilityByPage facilityServerSyncDataByServerId deleteFacilitySoftwareConfig updateFacilitySoftwareConfig updateFacilitySoftwareConfigStatus startFullMappingAggregation generateServerPDUMapping syncHostnameByIp readVROJobs readVCJobs readJobByType tempHumidityMapping createSddcSoftwareConfig deleteSddcSoftwareConfig updateSddcSoftwareConfig updateSddcSoftwareConfigStatus readSddcSoftwareConfigByID syncDataByServerId readVROByUser readSddcSoftwareConfigByVC readSddcSoftwareConfigByUserAndPage readVROsSddcSoftwareConfigByUser readSddcSoftwareConfigByTypeAndUser createSensorSetting readSensorSettingByID readSensorSettingsByPage updateSensorSetting deleteSensorSetting deleteUser updateUser readUserByID readUserByUserName readUserByPage readUsers createRole readRole readRolesByPage deleteRole updateRole readPrivileges readSystemSummary Default_Access_Privilege wormholeRole_default_admin wormholeRole_default_api wormholeRole_default_user WormholeUser_default_admin