name: test nlyte-worker

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: test nlyte-worker
      run: |
        export FLOWGATEPWD=$PWD
        cd $FLOWGATEPWD/flowgate-common
        sudo mvn clean install
        cd $FLOWGATEPWD/common-restclient
        sudo mvn clean install
        cd $FLOWGATEPWD/worker-jobs
        sudo mvn clean install
        cd $FLOWGATEPWD/nlyte-worker
        sudo mvn clean test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          flags: nlyte
          name: codecov-nlyte-worker
          fail_ci_if_error: true
